### ISSUE TITLE
[Enhancement]: Expose the route service

### ISSUE THREAD

**Issue by cooktheryan** [openshift/microshift#334]
#### What would you like to be added: 
I would like to be able to access exposed the router services

#### Why is this needed:
We should embrace an experience similar to OpenShift routes so that usage between the two platforms is somewhat similar and we are not forcing users to open node ports per application unless desired

**Comment by mangelajo** [comment]
We need to create something like this by default, and then, on the microshift container image redirect 80 to 30001 and 443 to 30002. On host installs may be we can use an nftables/iptables redirect.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: openshift-ingress
spec:
  type: NodePort
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: default
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30002
```
