### ISSUE TITLE
[Enhancement] Support DeploymentConfigs

### ISSUE THREAD

**Issue by cooktheryan** [openshift/microshift#459]
#### What happened:
Attempted to deploy the following
```
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1 
metadata:
  name: frontend
spec:
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - name: helloworld
          image: nginx
  replicas: 5
  selector:
    name: frontend
  strategy:
    type: Rolling
    rollingParams:
      pre:
        failurePolicy: Abort
        execNewPod:
          containerName: helloworld 
          command: [ "/usr/bin/command", "arg1", "arg2" ] 
          env: 
            - name: CUSTOM_VAR1
              value: custom_value1
```

In events the following err
```
1s          Warning   Failed                           pod/frontend-2-deploy       Failed to pull image "quay.io/openshift/origin-deployer:unknown": rpc error: code = Unknown desc = Error reading manifest unknown in quay.io/openshift/origin-deployer: manifest unknown: manifest unknown
```

#### What you expected to happen:
Deployment config to be deloyed

#### How to reproduce it (as minimally and precisely as possible):

1. Create deployment config
2. check logs

#### Environment:
- Microshift version (use `microshift version`): 4.8.0-0.microshift-2021-11-11-151353-3-g49ce62e
- Hardware configuration: amd64
- OS (e.g: `cat /etc/os-release`): RHEL 8.5
- Kernel (e.g. `uname -a`): Linux binary-small.example.com 4.18.0-348.el8.x86_64 #1 SMP Mon Oct 4 12:17:22 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

- Others:
