### ISSUE TITLE
Single api with multiple endpoints in microshift ingress

### ISSUE THREAD

**Issue by neetabisht** [openshift/microshift#4653]
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: computer-settings-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: computer-settings
      http:
        paths:
          - path: /update_timezone
            pathType: Prefix
            backend:
              service:
                name: computer-settings
                port:
                  number: 8080
          - path: /update_ntp_servers
            pathType: Prefix
            backend:
              service:
                name: computer-settings
                port:
                  number: 8080``
```

when i send request following above ingress file with below requests, it works perfectly fine.
  curl -X POST http://computer-settings/update_timezone -H "Content-Type: application/json" -d "{\"timezone\": \"Asia/Kolkata\"}" 
  
curl -X POST http://computer-settings/update_ntp_servers -H "Content-Type: application/json" -d "{\"params\": [\"192.168.0.12\", \"192.168.0.13\"]}"

But when i want to have single path /csbapi for 2 different endpoints update_timezone and update_ntp_servers then it doesn't work. pls refer below screen shot for this.

![Image](https://github.com/user-attachments/assets/3bbcc2fe-075e-4067-bc0d-c53c698817d2)

Setup: Using microshift cluster in Rhel9.4
Could you please help me with this.
