### ISSUE TITLE
how to allow access to usb device from pod?

### ISSUE THREAD

**Issue by ikke-t** [openshift/microshift#4719]
Hi,

I want to run zigbee2mqtt pod in microshift. How do I get /dev/ttyACM0 shown into pod for radio access?

I assume a way around this would be running it all as root dropping the security. But I'd like to do it so the normal random uid would get access to device made available in the pod. By default the device is not shown in the container.

So far I have just tried showing the device via volume. Would probably need somethimg more:

```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: zigbee2mqtt
  namespace: z2m
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z2m
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "zigbee2mqtt"
        app.kubernetes.io/name: "zigbee2mqtt"
        app.kubernetes.io/version: "2.1.0"
        app: z2m
    spec:
      containers:
        - name: zigbee2mqtt
          image: "koenkk/zigbee2mqtt:2.1.0"
          # securityContext: {}
          securityContext:
            # capabilities:
              # add:
              # - SYS_ADMIN
            privileged: true
            runAsNonRoot: true
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Helsinki
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          volumeMounts:
            - mountPath: /app/data/
              name: data
            - mountPath: /app/data/configuration.yaml
              name: config-volume
              subPath: configuration.yaml
            - mountPath: /dev/ttyACM0
              name: ttyacm
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: z2m-data
        - name: config-volume
          configMap:
            name: zigbee2mqtt
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
```

I tried adding the couple of security context lines, but didn't yet do any scc bindings.
The error it gave was:

```
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "zigbee2mqtt" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "zigbee2mqtt" must set securityContext.capabilities.drop=["ALL"]), restricted volume types (volume "ttyacm" uses restricted volume type "hostPath"), runAsNonRoot != true (pod or container "zigbee2mqtt" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "zigbee2mqtt" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")           statefulset.apps/zigbee2mqtt created
```

And with this:

```
Warning: would violate PodSecurity "restricted:latest": privileged (container "zigbee2mqtt" must not set securityContext.privileged=true), allowPrivilegeEscalation != false (container "zigbee2mqtt" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "zigbee2mqtt" must set securityContext.capabilities.drop=["ALL"]), restricted volume types (volume "ttyacm" uses restricted volume type "hostPath"), seccompProfile (pod or container "zigbee2mqtt" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")                          statefulset.apps/zigbee2mqtt created
```

Any experience what to do?

```
[ikke@pimetal ~]$ rpm -q microshift                                                  microshift-4.17.14-202501240429.p0.gd53a093.assembly.4.17.14.el9.aarch64            
[ikke@pimetal ~]$ cat /etc/redhat-release                                            
Red Hat Enterprise Linux release 9.5 (Plow)
```

**Comment by eslutsky** [comment]
@ikke-t ,  check your namespace permissions
try adding :
```
  labels:
    openshift.io/run-level: "0"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged  
```
